fixxed the jumping cursor problem
codemirror/CodeMirror pull request #6621
Opened 2021-03-15 17:43 UTC by rogdevil

issue number
#6308 

description of the fix -
the problem was that the "touchend" and "touchmove" event was not working properly and causing the bug so i fixed then and a additional fix was that we have to add a inline style to the editor container which is
![image](https://user-images.githubusercontent.com/43280610/111197056-0356f400-85e4-11eb-9b49-3febbe15d3e7.png)

2021-03-15 18:59 UTC, alexanmtz requested changes
@rogdevil please remove all comments cause you shouldn't send comments of code in the final PR and please validate many scenarios as possible of the code, to be sure your changes will not affect the current behavior and verify the other examples.

2021-03-15 18:59 UTC, alexanmtz commented on src/edit/CodeMirror.js
> +      // alert("touch start", e.touches)
Please remove comments

2021-03-15 18:59 UTC, alexanmtz commented on src/edit/CodeMirror.js
> +    // on(d.scroller, "touchmove", function () {
Removing this will not impact another scenario? Please make sure all the scenarios will continue to work.

2021-03-15 18:59 UTC, alexanmtz commented on src/edit/CodeMirror.js
> +      // alert("touch end")
Same here, no need to send comments on the final code. Use the debug just for your local tests

2021-03-15 19:00 UTC, alexanmtz commented
@rogdevil please check the build failing for some code validation:
https://travis-ci.org/github/codemirror/CodeMirror/builds/763011194

```
src/edit/CodeMirror.js: Semicolon found (165:7)
src/edit/CodeMirror.js: Semicolon found (187:7)
```

2021-03-15 19:40 UTC, rogdevil commented
ok I have removed the comments ... i have tested the code very well and it does not cause any bugs at all :)

2021-03-15 21:25 UTC, marijnh commented
What I saw in the short time before I lost all patience was that you added a stray attribute to some demo, changed an arrow function to use `function` syntax, added a bunch of commented-out `alert` lines, and added two random spaces of indentation to several blocks of code. None those appear to be useful or and if you want me to review your patch, please make sure it only contains actual relevant changes.

2021-03-16 11:40 UTC, rogdevil commented
hey, i have made the fixes as you told, and also I didn't change any function to "function syntax" instead of arrow funtion syntax I have removed the alert statements. now about the changes that I made,

1. when I was investigating the bug the bug I found out that on android devices in chrome the event which is supposed to fire on "touchstart" was firing properly but the event "touchend" is not firing properly so I made some amends to the function firing on touch start by adding finishtouch() function to the end of touchstart event so that the corsor will be placed properly on the end of touch start event and we dont have to rely upon the touchend event to update the position of the cursor.
2. second thing as you know that "touchend" and "touchmove" events are causing the bug the touchend function fires multiple times on longpress event so the selection text was not working properly. in "touchend" event we have defined onlt 3 condition which are single tap, double tap and triple tap, as there is no condition which satisfies the longpress text selection event so we face problem on selecting the text thats why we are using "cm.setSelectText()" function so that our browser api auto detect the text selection behaviour and we don need to pass the starting point and anchor of the text selection like we were doing in the "cm.setSelection(range.anchor, range.head);" 
3. the third change that I made to was a demo html5 file so that we can reflect the changes made to script and disable the default behaviour of touch-action and execute the touch events that we have defined in the codemirror.js

I would love to know you thoughts on it .... :) @marijnh

2021-03-16 11:56 UTC, marijnh commented
> i have made the fixes as you told

That wasn't me, though.

> and also I didn't change any function to "function syntax" instead of arrow funtion syntax

I'm seeing this in the current patches:

```diff
-   on(d.scroller, "touchstart", e => {
+  on(d.scroller, "touchstart", function (e) {
```

Plus of course the whitespace changes and the commented-out lines are still there (seems your [last patch](https://github.com/codemirror/CodeMirror/pull/6621/commits/c9c598448200095079ed94d4897e4f5eff831b74) reintroduced those).

2021-03-18 18:19 UTC, closed without merging